### ISSUE TITLE
The Files under base folder are not indented correctly

### ISSUE THREAD

**Issue by gshiva** [thesystemninjaneer/kustomize-examples#1]
https://github.com/thesystemninjaneer/kustomize-examples/blob/4e91a72c54ccc7c4a23062fdb1c4f9756a57e9e8/frontend-app/base/deployment.yaml#L7 and others have their indentation incorrect causing the 
`kubectl kustomize apply -k base` 

fail with the following errors
`error: error validating "base": error validating data: [ValidationError(Deployment.spec): unknown field "matchLabels" 
in io.k8s.api.apps.v1.DeploymentSpec, ValidationError(Deployment.spec): unknown field "metadata" in io.k8s.api.apps.v1.DeploymentSpec, ValidationError(Deployment.spec): unknown field "spec" in io.k8s.api.apps.v1.DeploymentSpec, ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec, ValidationError(Deployment.spec): missing required field "template" in io.k8s.api.apps.v1.DeploymentSpec]; if you choose to ignore these errors, turn validation off with --validate=false
`
`error: error validating "overlays/dev": error validating data: ValidationError(Service.spec): unknown field "app" in io.k8s.api.core.v1.ServiceSpec; if you choose to ignore these errors, turn validation off with --validate=false        
`

**Comment by thesystemninjaneer** [comment]
Accepted contributed fix via Pr https://github.com/thesystemninjaneer/kustomize-examples/pull/2

**Comment by gshiva** [comment]
Closed by PR #2
